name: Deploy to EC2 via CodeBuild

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Start CodeBuild
        id: codebuild
        run: |
          BUILD_ID=$(aws codebuild start-build \
            --project-name assimetria-test-codebuild \
            --query 'build.id' \
            --output text)
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV

      - name: Wait for CodeBuild to complete
        run: |
          echo "Waiting for build $BUILD_ID to complete..."
          STATUS="IN_PROGRESS"
          while [[ "$STATUS" == "IN_PROGRESS" || "$STATUS" == "QUEUED" ]]; do
              sleep 10
              STATUS=$(aws codebuild batch-get-builds \
                  --ids "$BUILD_ID" \
                  --query 'builds[0].buildStatus' \
                  --output text)
              echo "Current build status: $STATUS"
          done
          if [[ "$STATUS" != "SUCCEEDED" ]]; then
              echo "Build failed with status: $STATUS"
              exit 1
          fi
          echo "Build succeeded!"

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/deploy_key.pem \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
              "bash -s" < .Assimetria-Test/infra/scripts/init-ec2.sh

REGION="eu-north-1"                                                         # AWS region
PROJECT_NAME="assimetria-test-codebuild"                                    # CodeBuild project name
EC2_USER="ec2-user"                                                         # SSH user
EC2_HOST="ec2-51-21-127-8.eu-north-1.compute.amazonaws.com"                 # EC2 public IP or DNS
EC2_KEY_PATH="~/.ssh/your-key.pem"           # Path to your SSH private key
REMOTE_SCRIPT_PATH="~/init-ec2.sh"           # Path on EC2 instance
